services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST}:${DB_PORT}:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "poetry run python manage.py migrate && poetry python manage.py collectstatic && poetry run python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "${APP_HOST}:${APP_PORT}:8000"
    depends_on:
      - db

volumes:
  db-data:
