# Generated by Django 5.0.6 on 2024-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                ("text", models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                "db_table": "phrases",
            },
        ),
    ]
