# Generated by Django 5.0.6 on 2024-05-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videomaker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phrase",
            name="text",
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
